version: '2'
services:
  mongo3:
    image: mongo:3.4
    hostname: mongo3
    restart: always
    entrypoint:
    - /usr/bin/mongod
    - --replSet
    - rs
    - --rest
    - --httpinterface
    expose:
    - '27017'
    - '28017'
    ports:
    - 30317:27017
    - 30318:27018
    volumes:
    - /green-music-mongos/mongo1:/data
  mongo2:
    image: mongo:3.4
    hostname: mongo2
    restart: always
    entrypoint:
    - /usr/bin/mongod
    - --replSet
    - rs
    - --rest
    - --httpinterface
    expose:
    - '27017'
    - '28017'
    ports:
    - 30217:27017
    - 30218:27018
    volumes:
    - /green-music-mongos/mongo2:/data
  mongo1:
    image: mongo:3.4
    hostname: mongo1
    links:
    - mongo2:mongo2
    - mongo3:mongo3
    restart: always
    entrypoint:
    - /usr/bin/mongod
    - --replSet
    - rs
    - --rest
    - --httpinterface
    expose:
    - '27017'
    - '28017'
    ports:
    - 30118:27018
    - 30117:27017
    volumes:
    - /green-music-mongos/mongo3:/data
  setup:
    image: daocloud.io/kmsbbb/green-music-mongo:latest
